services:
  random-gen:
    build:
      context: .
      dockerfile: ./Dockerfile  # Added ./ to be explicit
    container_name: random-string-app
    ports:
      - "3000:3000"
    restart: always
    labels:
      - "coolify.managed=true"
