services:
  visitor-counter:
    build: .
    container_name: persistent-counter
    ports:
      - "3000:3000"
    volumes:
      - stats-data:/data
    restart: always
    labels:
      - "coolify.managed=true"

volumes:
  stats-data:
    driver: local
