services:
  visitor-counter:
    build:
      context: .
      dockerfile: ./Dockerfile2
    container_name: persistent-counter
    ports:
      - "3000:3000"
    restart: always
    labels:
      - "coolify.managed=true"
